config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'devices#index'

  resources :devices, concerns: :paginatable
  resources :base_stations, concerns: :paginatable
end

app/models/actual_frequency.rb
class ActualFrequency
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/antenna_type.rb
class AntennaType
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bandwidth.rb
class Bandwidth
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/base_station.rb
class BaseStation
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  paginates_per 25

  has_many :devices
  belongs_to :firmware
  belongs_to :registration_frequency
  belongs_to :actual_frequency
  belongs_to :bandwidth
  belongs_to :antenna_type
  belongs_to :hardware

  field :billing_station_id, type: Integer
  field :name, type: String
  field :ip, type: String
  field :nagios, type: String
  field :ssid, type: String
  field :azimut, type: String
  field :correct, type: Boolean, default: false
  field :mac, type: String
  field :note, type: String
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  self.table_name =  'contract'
  self.primary_key = 'id'

  has_many :contract_parameter_type1, class_name: 'ContractParameterType1',
                                      foreign_key: 'cid'
  has_many :inet_services, class_name: 'InetService',
                           foreign_key: 'contractId'
end

app/models/contract_parameter_type1.rb
class ContractParameterType1 < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_1'
  self.primary_key = 'pid'

  belongs_to :contract, class_name: 'Contract',
                        foreign_key: 'cid'
end

app/models/contract_parameter_type2.rb
class ContractParameterType2 < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_2'
  self.primary_key = 'pid'

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/contract_parameter_type6.rb
class ContractParameterType6 < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_6'
  self.primary_key = 'pid'
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/contract_status.rb
class ContractStatus < ActiveRecord::Base
  self.table_name = 'contract_status'

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/device.rb
class Device
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Slug

  paginates_per 25

  belongs_to :base_station
  belongs_to :hardware

  field :contract_id, type: Integer
  field :contract_title, type: String
  field :contract_comment, type: String
  field :ip, type: String
  field :login, type: String
  field :frequency, type: String
  field :mac, type: String

  slug :login

  validates :login, :frequency, :ip, presence: true
end

app/models/firmware.rb
class Firmware
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :devices

  field :name, type: String
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_5'
  self.primary_key = 'cid'
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/hardware.rb
class Hardware
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations
  has_many :devices

  field :billing_hardware_id, type: Integer
  field :name, type: String
end

app/models/inet_service.rb
class InetService < ActiveRecord::Base
  self.table_name = 'inet_serv_14'

  belongs_to :contract, class_name: 'Contract', foreign_key: 'contractId'
  has_many :inet_resource_subscriptions, class_name: 'InetResourceSubscription', foreign_key: 'subscriberId'
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_phone'
  self.primary_key = 'cid'
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/registration_frequency.rb
class RegistrationFrequency
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = 'user'
  self.primary_key = 'id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable

  def self.authenticate(username, password)
    User::BillingAuthenticator.new(username, password).authenticate
  end

  def encrypted_password
    pswd
  end
end

app/controllers/base_stations_controller.rb
class BaseStationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @base_stations = BaseStation.order_by(updated_at: 'desc').page(params[:page])
  end

  def new
    @base_station = BaseStation.new
  end

  def create
    @base_station = BaseStation.new(create_params)
    if @base_station.save
      redirect_to @base_station
    else
      render :new
    end
  end

  def show
    @base_station = BaseStation.find(params[:id])
  end

  def edit
    @base_station = BaseStation.find(params[:id])
  end

  def update
    @base_station = BaseStation.find(params[:id])
    if @base_station.update(update_params)
      redirect_to @base_station
    else
      render :edit
    end
  end

  def delete
    @base_station = BaseStation.find(params[:id])
  end

  def destroy
    @base_station = BaseStation.find(params[:id])
    @base_station.destroy
    redirect_to @base_station
  end

  def create_params
    params.require(:base_station).permit(:billing_station_id, :name, :nagios, :ssid, :azimut, :correct, :ip, :mac, :note, 
      :hardware_id, :firmware_id, :registration_frequency_id, :actual_frequency_id, :bandwidth_id, :antenna_type_id)
  end

  alias update_params create_params
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  rescue_from Device::Services::InetNotFound, with: :inet_not_found

  def index
    @devices = Device.order_by(created_at: 'desc').page(params[:page])
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(create_params)
    if @device.save
      @contract = Device::Services::Create.new(@device).contract
      redirect_to @device
    else
      render :new
    end
  end

  def show
    @device = Device.find(params[:id])
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])
    if @device.update(update_params)
      @contract = Device::Services::Create.new(@device).contract
      @contract.contract_parameter_type1.where(pid: 75).update_all(val: @device.frequency)
      redirect_to @device
    else
      render :edit
    end
  end

  def delete
    @device = Device.find(params[:id])
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to @device
  end

  def create_params
    params.require(:device).permit(:login, :frequency, :mac, :hardware_id, :base_station_id)
  end

  alias update_params create_params

  def inet_not_found
    last = Device.find_by(login: @device.login)
    last.destroy
    render :failing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_stations_helper.rb
module BaseStationsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/base_stations/_form.html.haml
%h1 Форма для заполнения
= simple_form_for(@base_station, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  .form-actions
    = f.input :billing_station_id, label: 'Billing Id'
  .form-actions
    = f.input :name, label: 'Name'
  .form-actions
    = f.input :ip, label: 'IP'
  .form-actions
    = f.input :nagios, label: 'Nagios'
  .form-actions
    = f.input :ssid, label: 'Ssid'
  .form-actions
    = f.input :azimut, label: 'Azimut'
  .form-actions
    = f.association :hardware, label: 'Hardware'
  .form-actions
    = f.input :mac
  .form-actions
    = f.association :firmware, label: 'Firmware'
  .form-actions
    = f.association :registration_frequency, label: 'Registered Frequency'
  .form-actions
    = f.association :actual_frequency, label: 'Actual Frequency'
  .form-actions
    = f.association :bandwidth, label: 'Bandwidth'
  .form-actions
    = f.association :antenna_type, label: 'Antenna Type'
  .checkbox
    = f.input_field :correct, as: :boolean, inline_label: true, label: false
  .form-actions
    = f.input :note, label: 'Note', as: :text, input_html: { 'rows' => 5}
  .form-actions
    = f.button :submit, "Отправить данные"

app/views/base_stations/edit.html.haml
= render 'form'

app/views/base_stations/index.html.haml
%div
  = link_to "new", new_base_station_path, class: 'btn btn-primary'
%table.table.table-condensed
  %thead
    %tr
      %th name
      %th ip
      %th nagios
      %th ssid
      %th azimut
      %th firmware
      %th hardware
      %th mac
      %th reg.freq
      %th actual freq
      %th bandwidth
      %th antenna type
      %th actions
  %tbody
    - @base_stations.each do |base|
      - if base.registration_frequency.name.eql?(base.actual_frequency.name)
        %tr.success
          %td= base.name
          %td= base.ip
          %td= base.nagios
          %td= base.ssid
          %td= base.azimut
          %td= base.firmware.name
          %td= base.hardware.name
          %td= base.mac
          %td= base.registration_frequency.name
          %td= base.actual_frequency.name
          %td= base.bandwidth.name
          %td= base.antenna_type.name
          %td
            = link_to 'Edit', edit_base_station_path(base.to_param), class: 'btn btn-warning'
            = link_to "Delete", base_station_path(base.to_param), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-danger'
      - else
        %tr.error
          %td= base.name
          %td= base.ip
          %td= base.nagios
          %td= base.ssid
          %td= base.azimut
          %td= base.firmware.name
          %td= base.hardware.name
          %td= base.mac
          %td= base.registration_frequency.name
          %td= base.actual_frequency.name
          %td= base.bandwidth.name
          %td= base.antenna_type.name
          %td
            = link_to 'Edit', edit_base_station_path(base.to_param), class: 'btn btn-warning'
            = link_to "Delete", base_station_path(base.to_param), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-danger'
#pagination
  = paginate @base_stations

app/views/base_stations/new.html.haml
= render 'form'

app/views/base_stations/show.html.haml
.container
  %div
    = @base_station.name
  %div
    = @base_station.ip
  %div
    = @base_station.nagios
  %div
    = @base_station.ssid
  %div
    = @base_station.azimut
  %div
    = @base_station.firmware.name
  %div
    = @base_station.hardware.name
  %div
    = @base_station.mac
  %div
    = @base_station.registration_frequency.name
  %div
    = @base_station.actual_frequency.name
  %div
    = @base_station.bandwidth.name
  %div
    = @base_station.antenna_type.name