config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  root 'devices#index'

  resources :devices, concerns: :paginatable
  resources :base_stations, concerns: :paginatable
end

app/models/actual_frequency.rb
class ActualFrequency
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/antenna_type.rb
class AntennaType
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bandwidth.rb
class Bandwidth
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/base_station.rb
class BaseStation
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  paginates_per 25

  has_many :devices
  belongs_to :firmware
  belongs_to :registration_frequency
  belongs_to :actual_frequency
  belongs_to :bandwidth
  belongs_to :antenna_type
  belongs_to :hardware

  field :billing_station_id, type: Integer
  field :name, type: String
  field :ip, type: String
  field :nagios, type: String
  field :ssid, type: String
  field :azimut, type: String
  field :correct, type: Boolean, default: false
  field :mac, type: String
  field :note, type: String
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  self.table_name =  'contract'
  self.primary_key = 'id'

  has_many :contract_parameter_type1, class_name: 'ContractParameterType1',
                                      foreign_key: 'cid'
  has_many :inet_services, class_name: 'InetService',
                           foreign_key: 'contractId'
end

app/models/contract_parameter_type1.rb
class ContractParameterType1 < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_1'
  self.primary_key = 'pid'

  belongs_to :contract, class_name: 'Contract',
                        foreign_key: 'cid'
end

app/models/contract_status.rb
class ContractStatus < ActiveRecord::Base
  self.table_name = 'contract_status'

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/device.rb
class Device
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Slug

  paginates_per 25

  belongs_to :base_station
  belongs_to :hardware

  field :contract_id, type: Integer
  field :contract_title, type: String
  field :contract_comment, type: String
  field :ip, type: String
  field :login, type: String
  field :frequency, type: String
  field :mac, type: String

  slug :login

  validates :login, :frequency, :ip, presence: true
end

app/models/firmware.rb
class Firmware
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :devices

  field :name, type: String
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_5'
  self.primary_key = 'cid'
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/hardware.rb
class Hardware
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations
  has_many :devices

  field :billing_hardware_id, type: Integer
  field :name, type: String
end

app/models/inet_service.rb
class InetService < ActiveRecord::Base
  self.table_name = 'inet_serv_14'

  belongs_to :contract, class_name: 'Contract', foreign_key: 'contractId'
  has_many :inet_resource_subscriptions, class_name: 'InetResourceSubscription', foreign_key: 'subscriberId'
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  self.table_name = 'contract_parameter_type_phone'
  self.primary_key = 'cid'
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/registration_frequency.rb
class RegistrationFrequency
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  has_many :base_stations

  field :name, type: String
end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = 'user'
  self.primary_key = 'id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable

  def self.authenticate(username, password)
    User::BillingAuthenticator.new(username, password).authenticate
  end

  def encrypted_password
    pswd
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  rescue_from Device::Services::InetNotFound, with: :inet_not_found

  def index
    @devices = Device.order_by(created_at: 'desc').page(params[:page])
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(create_params)
    if @device.save
      @contract = Device::Services::Create.new(@device).contract
      redirect_to @device
    else
      render :new
    end
  end

  def show
    @device = Device.find(params[:id])
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])
    if @device.update(update_params)
      @contract = Device::Services::Create.new(@device).contract
      @contract.contract_parameter_type1.where(pid: 75).update_all(val: @device.frequency)
      redirect_to @device
    else
      render :edit
    end
  end

  def delete
    @device = Device.find(params[:id])
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to @device
  end

  def create_params
    params.require(:device).permit(:login, :frequency, :mac, :hardware_id, :base_station_id)
  end

  alias update_params create_params

  def inet_not_found
    last = Device.find_by(login: @device.login)
    last.destroy
    render :failing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_stations_helper.rb
module BaseStationsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/layouts/_footer.html.haml
.container
  .row
    .col-lg-12
      &copy; ООО Крыминфоком
      = Time.now.year
      г.

app/views/layouts/_header.html.haml
.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "ООО Крыминфоком", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Главная" , root_path
        %li= link_to "Абонентские устройства", devices_path
        %li= link_to "Базовые станции", base_stations_path
        - if user_signed_in?
          %li=link_to('Logout', destroy_user_session_path, :method => :delete)
        - else
          %li=link_to('Login', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ООО Крыминфоком
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/header'
    %section.wrapper
      .container-fluid
        .row
          .col-lg-12
            = yield
    %footer
      = render 'layouts/footer'

app/views/layouts/authenticate.html.haml
!!!
%html
  %head
    %title ООО Крыминфоком
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %section.authenticate
      %main
        = yield 